{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ror-cluster-agent.fullname" . }}:config-reader-crb
subjects:
- kind: ServiceAccount
  name: {{ include "ror-cluster-agent.serviceAccountName" . }}
  namespace: {{.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: {{ include "ror-cluster-agent.fullname" . }}:config-read-cr
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ror-cluster-agent.fullname" . }}:secret-rb
  namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ror-cluster-agent.fullname" . }}:secret-role
subjects:
- kind: ServiceAccount
  name: {{ include "ror-cluster-agent.serviceAccountName" . }}
  namespace: {{.Release.Namespace}}
{{- end }}
