debuglevel: INFO
replicaCount: 1
api: https://api.ror.sky.test.nhn.no
secretname: ror-secret
image:
  repository: ghcr.io/norskhelsenett/ror-cluster-agent
  pullPolicy: Always
  tag: "2.0.1"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: "ror-cluster-agent"
serviceAccount:
  create: false
  name: ror-cluster-agent-sa
podAnnotations: {}
rbac:
  create: false
podSecurityContext:
  runAsNonRoot: true
  fsGroup: 2000
  runAsUser: 1001
  runAsGroup: 1001
  supplementalGroups: [501]
securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - ALL
resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
